#CodeAssist project settings
#Sat Sep 26 10:21:29 GMT+01:00 2026
tree.expanded.Project=dir\:/storage/emulated/0/Android/data/com.tyron.code/files/codeassist/projects/yuvextech.github.io/components\ndir\:/storage/emulated/0/Android/data/com.tyron.code/files/codeassist/projects/yuvextech.github.io/.platform\nworkspace
