#CodeAssist project settings
#Sun Oct 04 12:26:36 GMT+01:00 2026
tree.expanded.Project=dir\:/storage/emulated/0/Android/data/com.tyron.code/files/codeassist/projects/yuvextech.github.io/.github/workflows\ndir\:/storage/emulated/0/Android/data/com.tyron.code/files/codeassist/projects/yuvextech.github.io/components\nworkspace\ndir\:/storage/emulated/0/Android/data/com.tyron.code/files/codeassist/projects/yuvextech.github.io/public
